name: LwLogic2
main: org.money.money.Main
version: 1.0
api-version: 1.21

commands:
  endgame:
    description: Force end match in current world
    usage: /endgame
    permission: lwlogic2.endgame

permissions:
  lwlogic2.endgame:
    default: op
