name: LastWarriors0
main: org.money.money.Main
version: 1.0
api-version: 1.21

commands:
  kitgive:
    description: Give kit items for heroes (Ganyu, HuTao)
    usage: |
      /kitgive Ganyu <bow|bud|ult> [player]
      /kitgive HuTao <homa|pyro> [player]
    aliases: [kg]
    permission: kits.give

permissions:
  kits.give:
    description: Allow using /kitgive
    default: op
